name: Brakeman Scan

on:
  push:
    #branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    #branches: [ main ]
  schedule:
    - cron: '22 11 * * 2'

jobs:
  brakeman-scan:
    name: Brakeman Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.0
#        bundler-cache: true

    - name: Setup Brakeman
      env:
        BRAKEMAN_VERSION: '5.4.0'
      run: |
        gem install brakeman --version $BRAKEMAN_VERSION

    # Execute Brakeman CLI and generate a SARIF output with the security issues identified during the analysis
    - name: Scan
      continue-on-error: true
      run: |
        brakeman -f sarif -o output.sarif.json .

    # Upload the SARIF file generated in the previous step
    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: output.sarif.json
