name: Linters

on:
  push:
  pull_request:

jobs:
  tests:
    name: Linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
          bundler-cache: true

#      - name: Setup Node
#        uses: actions/setup-node@v2
#        with:
#          node-version: 16
#          cache: yarn
#
#      - name: Install packages
#        run: |
#          yarn install --pure-lockfile

      - name: Run linters
        run: |
          bin/rubocop --parallel
